<?php

/**
 * @param array $fields
 * @param array $data
 */
return function (array $fields, array $data = []) {
    ?>
    <html>
    <head>
        <link
                rel="stylesheet"
                href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
                integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
                crossorigin="anonymous"
        >
    </head>
    <body>
    <div class="container">
        <h1 class="title">
            Hello World
        </h1>
        <p class="subtitle">
            Using <strong>Bootstrap</strong>!
        </p>
    </div>
    <div class="container">
        <form>
            <?php
            foreach ($fields as $field) {
                $this->renderField($field, pick($data, $field['id']));
            }
            ?>
        </form>
    </div>
    </body>
    </html>
    <?php
};
