<?php

/**
 * @param array $field
 */
return function (array $field) {
    ?>
    <div class="field">
        <label class="label" for="<?php echo pick($field, 'name'); ?>">
            <?php echo pick($field, 'label'); ?>
        </label>
        <div class="control">
            <input
                    id="<?php echo pick($field, 'id'); ?>"
                    name="<?php echo pick($field, 'name'); ?>"
                    type="<?php echo pick($field, 'type'); ?>"
                    class="input <?php echo pick($field, 'class'); ?>"
                    aria-describedby="<?php echo pick($field, 'aria'); ?>"
                    placeholder="<?php echo pick($field, 'placeholder'); ?>"
            >
            <small class="form-text text-muted"><?php echo pick($field, 'help'); ?></small>
        </div>
    </div>
    <?php
};
