<?php

/**
 * @param array $field
 */
return function (array $field) {
    $options = pick($field, 'options', []);
    ?>
    <div class="field">
        <label class="label" for="<?php echo pick($field, 'id'); ?>">
            <?php echo pick($field, 'label'); ?>
        </label>
        <div class="control">
            <div class="select">
                <select
                    class="<?php echo pick($field, 'class'); ?>"
                    aria-describedby="<?php echo pick($field, 'aria'); ?>"
                    name="<?php echo pick($field, 'name'); ?>"
                    id="<?php echo pick($field, 'id'); ?>"
                    <?php echo (pick($field, 'multiple') ? 'multiple' : ''); ?>
                >
                    <?php
                    foreach ($options as $option) {
                        ?>
                        <option value="<?php echo pick($option, 'value'); ?>">
                            <?php echo pick($option, 'label'); ?>
                        </option>
                        <?php
                    }
                    ?>
                </select>
            </div>
        </div>
        <small class="form-text text-muted"><?php echo pick($field, 'help'); ?></small>
    </div>
    <?php
};
